var data = {
    portfolio: [{
            "projectName": "Personal Branding",
            "data-index": "0",
            "id": "personalBrand",
            "class1": "picture1Personal",
            "class2": "picture2Personal",
            "class2": "picture3Personal",
            "jobType": "Grafic Design",
            "frameworks": "Photoshop",
            "picture": "https://image.ibb.co/idyOym/personal_Brand.png",
            "picture2": "",
            "picture3": "",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vitae malesuada libero. Suspendisse vitae nisl ornare, hendrerit nibh a, dignissim libero. Fusce vitae fringilla lectus, ac ullamcorper est. Suspendisse pellentesque congue odio, at tincidunt metus consequat vel. Maecenas nec nulla vehicula, ultricies augue eget, dictum enim. Sed tempor libero vel vehicula vestibulum. Donec nibh turpis, luctus et euismod non, malesuada eu eros.",
            "frameworksUsed": [{
                "photoshopClass": "devicon-photoshop-plain",
                "illustrator": "devicon-illustrator-plain",
            }],
    }, {
            "projectName": "3D Lowpoly",
            "data-index": "1",
            "id": "lowpoly",
            "class1": "picture1Lowpoly",
            "class2": "picture2Lowpoly",
            "class3": "picture3Lowpoly",
            "jobType": "Illustration",
            "frameworks": "Blender | Photoshop",
            "picture": "https://image.ibb.co/gDdTW6/lowpoly2.png",
            "picture2": "https://image.ibb.co/ew9AB6/lowpoly.png",
            "picture3": "https://image.ibb.co/cAmJym/lowpoly3.png",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vitae malesuada libero. Suspendisse vitae nisl ornare, hendrerit nibh a, dignissim libero. Fusce vitae fringilla lectus, ac ullamcorper est. Suspendisse pellentesque congue odio, at tincidunt metus consequat vel. Maecenas nec nulla vehicula, ultricies augue eget, dictum enim. Sed tempor libero vel vehicula vestibulum. Donec nibh turpis, luctus et euismod non, malesuada eu eros.",

            "frameworksUsed": [{
                "photoshopClass": "devicon-photoshop-plain",
            }],
    }, {
            "projectName": "Barber's Template",
            "data-index": "2",
            "id": "barbersTemplate",
            "class1": "picture1Template",
            "class2": "picture2Template",
            "class3": "picture3Template",
            "jobType": "Front-End Development",
            "frameworks": "HTML 5 | CSS3 | Javascript | Jquery",
            "picture": "https://image.ibb.co/efjU8b/barbers_Template_project.png",
            "picture2": "https://image.ibb.co/nn11Jm/template.png",
            "picture3": "",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vitae malesuada libero. Suspendisse vitae nisl ornare, hendrerit nibh a, dignissim libero. Fusce vitae fringilla lectus, ac ullamcorper est. Suspendisse pellentesque congue odio, at tincidunt metus consequat vel. Maecenas nec nulla vehicula, ultricies augue eget, dictum enim. Sed tempor libero vel vehicula vestibulum. Donec nibh turpis, luctus et euismod non, malesuada eu eros.",
            "frameworksUsed": [{
                "html5Class": "devicon-html5-plain-wordmark",

                "css3Class": "devicon-css3-plain-wordmark",

                "javascriptClass": "devicon-javascript-plain",

                "jqueryClass": "devicon-jquery-plain",
            }],
    }, {
            "projectName": "SPA Design",
            "data-index": "3",
            "id": "spaDesign",
            "class1": "picture1Spa",
            "class2": "picture2Spa",
            "class3": "picture3Spa",
            "jobType": "Front-End Development",
            "frameworks": "HTML 5 | CSS3 | Javascript | Jquery",
            "picture": "https://image.ibb.co/kaE5dm/stack1.png",
            "picture2": "https://image.ibb.co/n8sxr6/stack2.png",
            "picture3": "https://image.ibb.co/n1mU4R/stack3.png",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vitae malesuada libero. Suspendisse vitae nisl ornare, hendrerit nibh a, dignissim libero. Fusce vitae fringilla lectus, ac ullamcorper est. Suspendisse pellentesque congue odio, at tincidunt metus consequat vel. Maecenas nec nulla vehicula, ultricies augue eget, dictum enim. Sed tempor libero vel vehicula vestibulum. Donec nibh turpis, luctus et euismod non, malesuada eu eros.",
            "frameworksUsed": [{
                "html5Class": "devicon-html5-plain-wordmark",
                "css3Class": "devicon-css3-plain-wordmark",
                "javascriptClass": "devicon-javascript-plain",
                "jqueryClass": "devicon-jquery-plain",
                "google": "devicon-google-plain",
            }],
    },{
            "projectName": "College in 3D",
            "data-index": "4",
            "id": "Modeling",
            "class1": "picture13D",
            "class2": "picture23D",
            "class3": "picture33D",
            "jobType": "3D Modeling",
            "frameworks": "Blender | Photoshop",
            "picture": "https://image.ibb.co/k16wjR/college.png",
            "picture2": "https://image.ibb.co/fOATym/college3.png",
            "picture3": "../img/",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vitae malesuada libero. Suspendisse vitae nisl ornare, hendrerit nibh a, dignissim libero. Fusce vitae fringilla lectus, ac ullamcorper est. Suspendisse pellentesque congue odio, at tincidunt metus consequat vel. Maecenas nec nulla vehicula, ultricies augue eget, dictum enim. Sed tempor libero vel vehicula vestibulum. Donec nibh turpis, luctus et euismod non, malesuada eu eros.",
            "frameworksUsed": [{
                "photoshopClass": "devicon-photoshop-plain",
            }],
    },
    ]
}
